### ISSUE TITLE
Debug problem for main.py

### ISSUE THREAD

**Issue by Morethan123** [fpv-iplab/rulstm#5]
Hi, @antoninofurnari 
I am studying your work and code.So i choose debug mode in the IDE.
But when i arrive at get_scores() [function] in the main.py, i got the error.

Traceback (most recent call last):
  File "/home/shaojie/pycharm-community-2018.3.7/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/shaojie/pycharm-community-2018.3.7/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/shaojie/pycharm-community-2018.3.7/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/shaojie/pycharm-community-2018.3.7/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/media/shaojie/Software/Anticipate_egocentric_action/rulstm/RULSTM/main.py", line 501, in <module>
    main()
  File "/media/shaojie/Software/Anticipate_egocentric_action/rulstm/RULSTM/main.py", line 482, in main
    verb_scores, noun_scores, action_scores, ids = get_scores(model, loader)
  File "/media/shaojie/Software/Anticipate_egocentric_action/rulstm/RULSTM/main.py", line 233, in get_scores
    for batch in loader:
  File "/home/shaojie/anaconda3/envs/rulstm/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 626, in __next__
    self._shutdown_workers()
  File "/home/shaojie/anaconda3/envs/rulstm/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 713, in _shutdown_workers
    w.join()
  File "/home/shaojie/anaconda3/envs/rulstm/lib/python3.7/multiprocessing/process.py", line 140, in join
    res = self._popen.wait(timeout)
  File "/home/shaojie/anaconda3/envs/rulstm/lib/python3.7/multiprocessing/popen_fork.py", line 48, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/shaojie/anaconda3/envs/rulstm/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt

Hope to receive your reply! Thank you!

**Comment by antoninofurnari** [comment]
Hello,
Thank you for your interest in our code!

Just from the log it's hard to say. However, as there is a problem in "next" in dataloader.py, I guess the exception is not triggered directly from the code of this repository. Maybe it's something realted to the dataloader not being able to fetch data from the disk. 

Is the data (lmdb database) in the correct location? 

Also, I'm noting you are using the test routines. Were you able to succesfully perform training? This would help understand if it is a data problem.

Best,
Antonino

**Comment by Morethan123** [comment]
HI @antoninofurnari 

I have downloaded pre-extracted features from download_data.sh that you have provided, but without download download_data_full.sh( because of the file size is too big).

And i also train rgb branch for action anticipation task without any error under your data(.mdb). The test mode where i encounter trouble is the fact that i use your iccv_model to test.All models have been downloaded. By the way, i get the epoch is 15, and the perf is 35.34 for anticipation task in Fusion mode (if i didn't misremember). 

Your work is admirable and detailed.It's helpful of me!

**Comment by antoninofurnari** [comment]
If you can succesfully train, then it should not be a data problem. I noted from the log that the line numbers you are obtaining errors at do not correspond to line numbers in the current version of the code. For instance, you obtain:

482, in main
verb_scores, noun_scores, action_scores, ids = get_scores(model, loader)

But that line of code is actually at line 479: https://github.com/fpv-iplab/rulstm/blob/master/RULSTM/main.py#L479

Can you try testing the code again on a freshly cloned version of the repo? This would rule out side-effects due to changes to the cose, which I could not help you with.

Thanks,
Antonino
